
package tk.ljyuan71.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LJYServiceImpl", targetNamespace = "http://impl.webservice.ljyuan71.tk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LJYServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.webservice.ljyuan71.tk/", className = "tk.ljyuan71.webservice.impl.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.webservice.ljyuan71.tk/", className = "tk.ljyuan71.webservice.impl.SayHelloResponse")
    @Action(input = "http://impl.webservice.ljyuan71.tk/LJYServiceImpl/sayHelloRequest", output = "http://impl.webservice.ljyuan71.tk/LJYServiceImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://impl.webservice.ljyuan71.tk/", className = "tk.ljyuan71.webservice.impl.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://impl.webservice.ljyuan71.tk/", className = "tk.ljyuan71.webservice.impl.LoginResponse")
    @Action(input = "http://impl.webservice.ljyuan71.tk/LJYServiceImpl/loginRequest", output = "http://impl.webservice.ljyuan71.tk/LJYServiceImpl/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
