
package tk.ljyuan71.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LJYServiceImplService", targetNamespace = "http://impl.webservice.ljyuan71.tk/", wsdlLocation = "http://localhost:10000/Webservice?wsdl")
public class LJYServiceImplService
    extends Service
{

    private final static URL LJYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LJYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LJYSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.ljyuan71.tk/", "LJYServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10000/Webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LJYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LJYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LJYServiceImplService() {
        super(__getWsdlLocation(), LJYSERVICEIMPLSERVICE_QNAME);
    }

    public LJYServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LJYSERVICEIMPLSERVICE_QNAME, features);
    }

    public LJYServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LJYSERVICEIMPLSERVICE_QNAME);
    }

    public LJYServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LJYSERVICEIMPLSERVICE_QNAME, features);
    }

    public LJYServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LJYServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LJYServiceImpl
     */
    @WebEndpoint(name = "LJYServiceImplPort")
    public LJYServiceImpl getLJYServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.ljyuan71.tk/", "LJYServiceImplPort"), LJYServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LJYServiceImpl
     */
    @WebEndpoint(name = "LJYServiceImplPort")
    public LJYServiceImpl getLJYServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.ljyuan71.tk/", "LJYServiceImplPort"), LJYServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LJYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LJYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LJYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
