package tk.ljyuan71.cxfwebservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import http.www_ljyuan71_tk._interface.wsdl.CxfWebService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.13
 * 2017-11-06T09:51:17.837+08:00
 * Generated source version: 3.1.13
 * 
 */
@WebServiceClient(name = "cxfWebServiceImpl", 
                  wsdlLocation = "http://localhost:8080/cxfws-server/services/cxfWebService?wsdl",
                  targetNamespace = "http://impl.cxfwebservice.ljyuan71.tk/") 
public class CxfWebServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.cxfwebservice.ljyuan71.tk/", "cxfWebServiceImpl");
    public final static QName CxfWebServiceImplPort = new QName("http://impl.cxfwebservice.ljyuan71.tk/", "CxfWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxfws-server/services/cxfWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CxfWebServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxfws-server/services/cxfWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CxfWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CxfWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxfWebServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CxfWebServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CxfWebServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CxfWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CxfWebService
     */
    @WebEndpoint(name = "CxfWebServiceImplPort")
    public CxfWebService getCxfWebServiceImplPort() {
        return super.getPort(CxfWebServiceImplPort, CxfWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfWebService
     */
    @WebEndpoint(name = "CxfWebServiceImplPort")
    public CxfWebService getCxfWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CxfWebServiceImplPort, CxfWebService.class, features);
    }

}
